name: pet_shop
description: petshop

version: 1.1.4+315

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dropdown_formfield: ^0.1.3
  dropdownfield: ^1.0.3
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.14.0
  firebase_auth: ^0.18.3
  firebase_storage: ^5.2.0
  # firebase_analytics: ^5.0.11
  firebase_core: ^0.5.0+1
  # firebase_database: ^3.0.0
  firebase_messaging: ^7.0.3

  shared_preferences: ^0.5.6+1
  fluttertoast: ^7.1.8
  image_picker: ^0.6.7+22

  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.3.2+2
  path_provider: ^1.1.2
  image: ^2.0.7
  intl: ^0.16.1
  intl_phone_field: ^1.4.2
  jitsi_meet: any
  geocoder: ^0.2.0
  getflutter: ^1.0.11
  email_validator: ^1.0.4
  google_maps_flutter: ^1.2.0
  google_map_location_picker: ^4.1.6
  flutter_localizations:
    sdk: flutter
  charts_flutter: ^0.10.0
  age: ^0.0.1
  badges: ^1.1.6
  rxdart: ^0.25.0
  rx_shared_preferences: ^1.3.5
  flutter_launcher_icons: ^0.8.1
  http: ^0.12.2
  google_sign_in: ^4.5.9
  flutter_rating_bar: ^3.2.0+1
  flutter_credit_card: 0.1.4
  flutter_culqi : ^0.5.2
  dropdown_search: ^0.4.8
  #  contact_picker: any
  #  flutter_sms: any
  flutter_share_me: ^0.9.2
  shortid: ^0.1.1
  native_pdf_view: ^3.9.1
  geolocator: ^6.0.0
  infinite_scroll_pagination: ^2.3.0
  lazy_loading_list: ^1.0.0
  lazy_load_scrollview: ^1.2.0

dev_dependencies:
  intl_translation: ^0.17.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "diseñador/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
          style: normal
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf

        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700

  assets:

    - images/
    - diseñador/SplashScreen2.png
    - diseñador/logo.png
    - diseñador/drawable/
    - diseñador/drawable/IconosCategorias/
    - diseñador/drawable/Servicios/
    - diseñador/drawable/Salud/
    - diseñador/drawable/Productos/
    - diseñador/drawable/Alimento1/
    - diseñador/drawable/Home2/
    - diseñador/Grupo592.png
    - assets/images/
    - assets/images/patas.png
    - images/terminos.pdf
    - images/sinproducto.jpg